# Generated by Django 5.1 on 2024-11-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='proovedores',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('ine', models.CharField(max_length=50)),
                ('permiso', models.CharField(max_length=50)),
                ('matricula', models.CharField(max_length=50)),
            ],
        ),
    ]
